# This is a basic workflow to help you get started with Actions
 
name: run test.py
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4

        with:
          python-version: '3.10' # install the python version needed
      - name: execute py script # run main.py
        run: python main.py
